version: "3.9"

services:
  backend:
    build: .
    image: logitrack-backend
    container_name: logitrack-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_logitrack
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1348MP
      JWT_SECRET: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: logitrack-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_logitrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1348MP
